print("Hello world!")
print("Hello Universe!")
print("Hello from the other side")
print ("It's me, Hi, I'm the problem it's me")
print("blank Space")
a=int(input("Enter the number:"))
b=int(input("Enter the number:"))
print("the sum:",a+b)
print("The product:",a*b)
